export const COUNTRY_LOCATION_DATA = {
    'Andaman and Nicobar Islands': [{ value: 'Port Blair', label: 'Port Blair' }],
    'Andhra Pradesh': [
      { label: 'Adoni', value: 'Adoni' },
      { label: 'Amaravati', value: 'Amaravati' },
      { label: 'Anantapur', value: 'Anantapur' },
      { label: 'Chandragiri', value: 'Chandragiri' },
      { label: 'Chittoor', value: 'Chittoor' },
      { label: 'Dowlaiswaram', value: 'Dowlaiswaram' },
      { label: 'Eluru', value: 'Eluru' },
      { label: 'Guntur', value: 'Guntur' },
      { label: 'Kadapa', value: 'Kadapa' },
      { label: 'Kakinada', value: 'Kakinada' },
      { label: 'Kurnool', value: 'Kurnool' },
      { label: 'Machilipatnam', value: 'Machilipatnam' },
      { label: 'Nagarjunakoṇḍa', value: 'Nagarjunakoṇḍa' },
      { label: 'Rajahmundry', value: 'Rajahmundry' },
      { label: 'Srikakulam', value: 'Srikakulam' },
      { label: 'Tirupati', value: 'Tirupati' },
      { label: 'Vijayawada', value: 'Vijayawada' },
      { label: 'Visakhapatnam', value: 'Visakhapatnam' },
      { label: 'Vizianagaram', value: 'Vizianagaram' },
      { label: 'Yemmiganur', value: 'Yemmiganur' },
    ],
    'Arunachal Pradesh': [{ value: 'Itanagar', label: 'Itanagar' }],
    Assam: [
      { value: 'Dhuburi', label: 'Dhuburi' },
      { value: 'Dibrugarh', label: 'Dibrugarh' },
      { value: 'Dispur', label: 'Dispur' },
      { value: 'Guwahati', label: 'Guwahati' },
      { value: 'Jorhat', label: 'Jorhat' },
      { value: 'Nagaon', label: 'Nagaon' },
      { value: 'Sivasagar', label: 'Sivasagar' },
      { value: 'Silchar', label: 'Silchar' },
      { value: 'Tezpur', label: 'Tezpur' },
      { value: 'Tinsukia', label: 'Tinsukia' },
    ],
    Bihar: [
      { value: 'Ara', label: 'Ara' },
      { value: 'Barauni', label: 'Barauni' },
      { value: 'Begusarai', label: 'Begusarai' },
      { value: 'Bettiah', label: 'Bettiah' },
      { value: 'Bhagalpur', label: 'Bhagalpur' },
      { value: 'Bihar Sharif', label: 'Bihar Sharif' },
      { value: 'Bodh Gaya', label: 'Bodh Gaya' },
      { value: 'Buxar', label: 'Buxar' },
      { value: 'Chapra', label: 'Chapra' },
      { value: 'Darbhanga', label: 'Darbhanga' },
      { value: 'Dehri', label: 'Dehri' },
      { value: 'Dinapur Nizamat', label: 'Dinapur Nizamat' },
      { value: 'Gaya', label: 'Gaya' },
      { value: 'Hajipur', label: 'Hajipur' },
      { value: 'Jamalpur', label: 'Jamalpur' },
      { value: 'Katihar', label: 'Katihar' },
      { value: 'Madhubani', label: 'Madhubani' },
      { value: 'Motihari', label: 'Motihari' },
      { value: 'Munger', label: 'Munger' },
      { value: 'Muzaffarpur', label: 'Muzaffarpur' },
      { value: 'Patna', label: 'Patna' },
      { value: 'Purnia', label: 'Purnia' },
      { value: 'Pusa', label: 'Pusa' },
      { value: 'Saharsa', label: 'Saharsa' },
      { value: 'Samastipur', label: 'Samastipur' },
      { value: 'Sasaram', label: 'Sasaram' },
      { value: 'Sitamarhi', label: 'Sitamarhi' },
      { value: 'Siwan', label: 'Siwan' },
    ],
    Chandigarh: [
      { value: 'Chandigarh', label: 'Chandigarh' },
      { value: 'Chhattisgarh', label: 'Chhattisgarh' },
      { value: 'Ambikapur', label: 'Ambikapur' },
      { value: 'Bhilai', label: 'Bhilai' },
      { value: 'Bilaspur', label: 'Bilaspur' },
      { value: 'Dhamtari', label: 'Dhamtari' },
      { value: 'Durg', label: 'Durg' },
      { value: 'Jagdalpur', label: 'Jagdalpur' },
      { value: 'Raipur', label: 'Raipur' },
      { value: 'Rajnandgaon', label: 'Rajnandgaon' },
    ],
    'Dadra and Nagar Haveli and Daman and Diu': [
      { value: 'Daman', label: 'Daman' },
      { value: 'Diu', label: 'Diu' },
      { value: 'Silvassa', label: 'Silvassa' },
    ],
    Delhi: [
      { value: 'Delhi', label: 'Delhi' },
      { value: 'New Delhi', label: 'New Delhi' },
    ],
    Goa: [
      { value: 'Madgaon', label: 'Madgaon' },
      { value: 'Panaji', label: 'Panaji' },
    ],
    Gujarat: [
      { value: 'Ahmadabad', label: 'Ahmadabad' },
      { value: 'Amreli', label: 'Amreli' },
      { value: 'Bharuch', label: 'Bharuch' },
      { value: 'Bhavnagar', label: 'Bhavnagar' },
      { value: 'Bhuj', label: 'Bhuj' },
      { value: 'Dwarka', label: 'Dwarka' },
      { value: 'Gandhinagar', label: 'Gandhinagar' },
      { value: 'Godhra', label: 'Godhra' },
      { value: 'Jamnagar', label: 'Jamnagar' },
      { value: 'Junagadh', label: 'Junagadh' },
      { value: 'Kandla', label: 'Kandla' },
      { value: 'Khambhat', label: 'Khambhat' },
      { value: 'Kheda', label: 'Kheda' },
      { value: 'Mahesana', label: 'Mahesana' },
      { value: 'Morbi', label: 'Morbi' },
      { value: 'Nadiad', label: 'Nadiad' },
      { value: 'Navsari', label: 'Navsari' },
      { value: 'Okha', label: 'Okha' },
      { value: 'Palanpur', label: 'Palanpur' },
      { value: 'Patan', label: 'Patan' },
      { value: 'Porbandar', label: 'Porbandar' },
      { value: 'Rajkot', label: 'Rajkot' },
      { value: 'Surat', label: 'Surat' },
      { value: 'Surendranagar', label: 'Surendranagar' },
      { value: 'Valsad', label: 'Valsad' },
      { value: 'Veraval', label: 'Veraval' },
    ],
    Haryana: [
      { value: 'Ambala', label: 'Ambala' },
      { value: 'Bhiwani', label: 'Bhiwani' },
      { value: 'Chandigarh', label: 'Chandigarh' },
      { value: 'Faridabad', label: 'Faridabad' },
      { value: 'Firozpur Jhirka', label: 'Firozpur Jhirka' },
      { value: 'Gurugram', label: 'Gurugram' },
      { value: 'Hansi', label: 'Hansi' },
      { value: 'Hisar', label: 'Hisar' },
      { value: 'Jind', label: 'Jind' },
      { value: 'Kaithal', label: 'Kaithal' },
      { value: 'Karnal', label: 'Karnal' },
      { value: 'Kurukshetra', label: 'Kurukshetra' },
      { value: 'Panipat', label: 'Panipat' },
      { value: 'Pehowa', label: 'Pehowa' },
      { value: 'Rewari', label: 'Rewari' },
      { value: 'Rohtak', label: 'Rohtak' },
      { value: 'Sirsa', label: 'Sirsa' },
      { value: 'Sonipat', label: 'Sonipat' },
    ],
    'Himachal Pradesh': [
      { value: 'Bilaspur', label: 'Bilaspur' },
      { value: 'Chamba', label: 'Chamba' },
      { value: 'Dalhousie', label: 'Dalhousie' },
      { value: 'Dharmshala', label: 'Dharmshala' },
      { value: 'Hamirpur', label: 'Hamirpur' },
      { value: 'Kangra', label: 'Kangra' },
      { value: 'Kullu', label: 'Kullu' },
      { value: 'Mandi', label: 'Mandi' },
      { value: 'Nahan', label: 'Nahan' },
      { value: 'Shimla', label: 'Shimla' },
      { value: 'Una', label: 'Una' },
    ],
    'Jammu and Kashmir': [
      { value: 'Anantnag', label: 'Anantnag' },
      { value: 'Baramula', label: 'Baramula' },
      { value: 'Doda', label: 'Doda' },
      { value: 'Gulmarg', label: 'Gulmarg' },
      { value: 'Jammu', label: 'Jammu' },
      { value: 'Kathua', label: 'Kathua' },
      { value: 'Punch', label: 'Punch' },
      { value: 'Rajouri', label: 'Rajouri' },
      { value: 'Srinagar', label: 'Srinagar' },
      { value: 'Udhampur', label: 'Udhampur' },
    ],
    Jharkhand: [
      { value: 'Bokaro', label: 'Bokaro' },
      { value: 'Chaibasa', label: 'Chaibasa' },
      { value: 'Deoghar', label: 'Deoghar' },
      { value: 'Dhanbad', label: 'Dhanbad' },
      { value: 'Dumka', label: 'Dumka' },
      { value: 'Giridih', label: 'Giridih' },
      { value: 'Hazaribag', label: 'Hazaribag' },
      { value: 'Jamshedpur', label: 'Jamshedpur' },
      { value: 'Jharia', label: 'Jharia' },
      { value: 'Rajmahal', label: 'Rajmahal' },
      { value: 'Ranchi', label: 'Ranchi' },
      { value: 'Saraikela', label: 'Saraikela' },
    ],
    Karnataka: [
      { value: 'Badami', label: 'Badami' },
      { value: 'Ballari', label: 'Ballari' },
      { value: 'Bengaluru', label: 'Bengaluru' },
      { value: 'Belagavi', label: 'Belagavi' },
      { value: 'Bhadravati', label: 'Bhadravati' },
      { value: 'Bidar', label: 'Bidar' },
      { value: 'Chikkamagaluru', label: 'Chikkamagaluru' },
      { value: 'Chitradurga', label: 'Chitradurga' },
      { value: 'Davangere', label: 'Davangere' },
      { value: 'Halebid', label: 'Halebid' },
      { value: 'Hassan', label: 'Hassan' },
      { value: 'Hubballi-Dharwad', label: 'Hubballi-Dharwad' },
      { value: 'Kalaburagi', label: 'Kalaburagi' },
      { value: 'Kolar', label: 'Kolar' },
      { value: 'Madikeri', label: 'Madikeri' },
      { value: 'Mandya', label: 'Mandya' },
      { value: 'Mangaluru', label: 'Mangaluru' },
      { value: 'Mysuru', label: 'Mysuru' },
      { value: 'Raichur', label: 'Raichur' },
      { value: 'Shivamogga', label: 'Shivamogga' },
      { value: 'Shravanabelagola', label: 'Shravanabelagola' },
      { value: 'Shrirangapattana', label: 'Shrirangapattana' },
      { value: 'Tumakuru', label: 'Tumakuru' },
      { value: 'Vijayapura', label: 'Vijayapura' },
    ],
    Kerala: [
      { value: 'Alappuzha', label: 'Alappuzha' },
      { value: 'Vatakara', label: 'Vatakara' },
      { value: 'Idukki', label: 'Idukki' },
      { value: 'Kannur', label: 'Kannur' },
      { value: 'Kochi', label: 'Kochi' },
      { value: 'Kollam', label: 'Kollam' },
      { value: 'Kottayam', label: 'Kottayam' },
      { value: 'Kozhikode', label: 'Kozhikode' },
      { value: 'Mattancheri', label: 'Mattancheri' },
      { value: 'Palakkad', label: 'Palakkad' },
      { value: 'Thalassery', label: 'Thalassery' },
      { value: 'Thiruvananthapuram', label: 'Thiruvananthapuram' },
      { value: 'Thrissur', label: 'Thrissur' },
    ],
    Ladakh: [
      { value: 'Kargil', label: 'Kargil' },
      { value: 'Leh', label: 'Leh' },
      { value: 'Madhya Pradesh', label: 'Madhya Pradesh' },
      { value: 'Balaghat', label: 'Balaghat' },
      { value: 'Barwani', label: 'Barwani' },
      { value: 'Betul', label: 'Betul' },
      { value: 'Bharhut', label: 'Bharhut' },
      { value: 'Bhind', label: 'Bhind' },
      { value: 'Bhojpur', label: 'Bhojpur' },
      { value: 'Bhopal', label: 'Bhopal' },
      { value: 'Burhanpur', label: 'Burhanpur' },
      { value: 'Chhatarpur', label: 'Chhatarpur' },
      { value: 'Chhindwara', label: 'Chhindwara' },
      { value: 'Damoh', label: 'Damoh' },
      { value: 'Datia', label: 'Datia' },
      { value: 'Dewas', label: 'Dewas' },
      { value: 'Dhar', label: 'Dhar' },
      { value: 'Dr. Ambedkar Nagar (Mhow)', label: 'Dr. Ambedkar Nagar (Mhow)' },
      { value: 'Guna', label: 'Guna' },
      { value: 'Gwalior', label: 'Gwalior' },
      { value: 'Hoshangabad', label: 'Hoshangabad' },
      { value: 'Indore', label: 'Indore' },
      { value: 'Itarsi', label: 'Itarsi' },
      { value: 'Jabalpur', label: 'Jabalpur' },
      { value: 'Jhabua', label: 'Jhabua' },
      { value: 'Khajuraho', label: 'Khajuraho' },
      { value: 'Khandwa', label: 'Khandwa' },
      { value: 'Khargone', label: 'Khargone' },
      { value: 'Maheshwar', label: 'Maheshwar' },
      { value: 'Mandla', label: 'Mandla' },
      { value: 'Mandsaur', label: 'Mandsaur' },
      { value: 'Morena', label: 'Morena' },
      { value: 'Murwara', label: 'Murwara' },
      { value: 'Narsimhapur', label: 'Narsimhapur' },
      { value: 'Narsinghgarh', label: 'Narsinghgarh' },
      { value: 'Narwar', label: 'Narwar' },
      { value: 'Neemuch', label: 'Neemuch' },
      { value: 'Nowgong', label: 'Nowgong' },
      { value: 'Orchha', label: 'Orchha' },
      { value: 'Panna', label: 'Panna' },
      { value: 'Raisen', label: 'Raisen' },
      { value: 'Rajgarh', label: 'Rajgarh' },
      { value: 'Ratlam', label: 'Ratlam' },
      { value: 'Rewa', label: 'Rewa' },
      { value: 'Sagar', label: 'Sagar' },
      { value: 'Sarangpur', label: 'Sarangpur' },
      { value: 'Satna', label: 'Satna' },
      { value: 'Sehore', label: 'Sehore' },
      { value: 'Seoni', label: 'Seoni' },
      { value: 'Shahdol', label: 'Shahdol' },
      { value: 'Shajapur', label: 'Shajapur' },
      { value: 'Sheopur', label: 'Sheopur' },
      { value: 'Shivpuri', label: 'Shivpuri' },
      { value: 'Ujjain', label: 'Ujjain' },
      { value: 'Vidisha', label: 'Vidisha' },
    ],
    Maharashtra: [
      { value: 'Ahmadnagar', label: 'Ahmadnagar' },
      { value: 'Akola', label: 'Akola' },
      { value: 'Amravati', label: 'Amravati' },
      { value: 'Aurangabad', label: 'Aurangabad' },
      { value: 'Bhandara', label: 'Bhandara' },
      { value: 'Bhusawal', label: 'Bhusawal' },
      { value: 'Bid', label: 'Bid' },
      { value: 'Buldhana', label: 'Buldhana' },
      { value: 'Chandrapur', label: 'Chandrapur' },
      { value: 'Daulatabad', label: 'Daulatabad' },
      { value: 'Dhule', label: 'Dhule' },
      { value: 'Jalgaon', label: 'Jalgaon' },
      { value: 'Kalyan', label: 'Kalyan' },
      { value: 'Karli', label: 'Karli' },
      { value: 'Kolhapur', label: 'Kolhapur' },
      { value: 'Mahabaleshwar', label: 'Mahabaleshwar' },
      { value: 'Malegaon', label: 'Malegaon' },
      { value: 'Matheran', label: 'Matheran' },
      { value: 'Mumbai', label: 'Mumbai' },
      { value: 'Nagpur', label: 'Nagpur' },
      { value: 'Nanded', label: 'Nanded' },
      { value: 'Nashik', label: 'Nashik' },
      { value: 'Osmanabad', label: 'Osmanabad' },
      { value: 'Pandharpur', label: 'Pandharpur' },
      { value: 'Parbhani', label: 'Parbhani' },
      { value: 'Pune', label: 'Pune' },
      { value: 'Ratnagiri', label: 'Ratnagiri' },
      { value: 'Sangli', label: 'Sangli' },
      { value: 'Satara', label: 'Satara' },
      { value: 'Sevagram', label: 'Sevagram' },
      { value: 'Solapur', label: 'Solapur' },
      { value: 'Thane', label: 'Thane' },
      { value: 'Ulhasnagar', label: 'Ulhasnagar' },
      { value: 'Vasai-Virar', label: 'Vasai-Virar' },
      { value: 'Wardha', label: 'Wardha' },
      { value: 'Yavatmal', label: 'Yavatmal' },
    ],
    Manipur: [{ value: 'Imphal', label: 'Imphal' }],
    Meghalaya: [
      { value: 'Cherrapunji', label: 'Cherrapunji' },
      { value: 'Shillong', label: 'Shillong' },
    ],
    Mizoram: [
      { value: 'Aizawl', label: 'Aizawl' },
      { value: 'Lunglei', label: 'Lunglei' },
    ],
    Nagaland: [
      { value: 'Kohima', label: 'Kohima' },
      { value: 'Mon', label: 'Mon' },
      { value: 'Phek', label: 'Phek' },
      { value: 'Wokha', label: 'Wokha' },
      { value: 'Zunheboto', label: 'Zunheboto' },
    ],
    Odisha: [
      { value: 'Balangir', label: 'Balangir' },
      { value: 'Baleshwar', label: 'Baleshwar' },
      { value: 'Baripada', label: 'Baripada' },
      { value: 'Bhubaneshwar', label: 'Bhubaneshwar' },
      { value: 'Brahmapur', label: 'Brahmapur' },
      { value: 'Cuttack', label: 'Cuttack' },
      { value: 'Dhenkanal', label: 'Dhenkanal' },
      { value: 'Kendujhar', label: 'Kendujhar' },
      { value: 'Konark', label: 'Konark' },
      { value: 'Koraput', label: 'Koraput' },
      { value: 'Paradip', label: 'Paradip' },
      { value: 'Phulabani', label: 'Phulabani' },
      { value: 'Puri', label: 'Puri' },
      { value: 'Sambalpur', label: 'Sambalpur' },
      { value: 'Udayagiri', label: 'Udayagiri' },
    ],
    Puducherry: [
      { value: 'Karaikal', label: 'Karaikal' },
      { value: 'Mahe', label: 'Mahe' },
      { value: 'Puducherry', label: 'Puducherry' },
      { value: 'Yanam', label: 'Yanam' },
    ],
    Punjab: [
      { value: 'Amritsar', label: 'Amritsar' },
      { value: 'Batala', label: 'Batala' },
      { value: 'Chandigarh', label: 'Chandigarh' },
      { value: 'Faridkot', label: 'Faridkot' },
      { value: 'Firozpur', label: 'Firozpur' },
      { value: 'Gurdaspur', label: 'Gurdaspur' },
      { value: 'Hoshiarpur', label: 'Hoshiarpur' },
      { value: 'Jalandhar', label: 'Jalandhar' },
      { value: 'Kapurthala', label: 'Kapurthala' },
      { value: 'Ludhiana', label: 'Ludhiana' },
      { value: 'Nabha', label: 'Nabha' },
      { value: 'Patiala', label: 'Patiala' },
      { value: 'Rupnagar', label: 'Rupnagar' },
      { value: 'Sangrur', label: 'Sangrur' },
    ],
    Rajasthan: [
      { value: 'Abu', label: 'Abu' },
      { value: 'Ajmer', label: 'Ajmer' },
      { value: 'Alwar', label: 'Alwar' },
      { value: 'Amer', label: 'Amer' },
      { value: 'Barmer', label: 'Barmer' },
      { value: 'Beawar', label: 'Beawar' },
      { value: 'Bharatpur', label: 'Bharatpur' },
      { value: 'Bhilwara', label: 'Bhilwara' },
      { value: 'Bikaner', label: 'Bikaner' },
      { value: 'Bundi', label: 'Bundi' },
      { value: 'Chittaurgarh', label: 'Chittaurgarh' },
      { value: 'Churu', label: 'Churu' },
      { value: 'Dhaulpur', label: 'Dhaulpur' },
      { value: 'Dungarpur', label: 'Dungarpur' },
      { value: 'Ganganagar', label: 'Ganganagar' },
      { value: 'Hanumangarh', label: 'Hanumangarh' },
      { value: 'Jaipur', label: 'Jaipur' },
      { value: 'Jaisalmer', label: 'Jaisalmer' },
      { value: 'Jalor', label: 'Jalor' },
      { value: 'Jhalawar', label: 'Jhalawar' },
      { value: 'Jhunjhunu', label: 'Jhunjhunu' },
      { value: 'Jodhpur', label: 'Jodhpur' },
      { value: 'Kishangarh', label: 'Kishangarh' },
      { value: 'Kota', label: 'Kota' },
      { value: 'Merta', label: 'Merta' },
      { value: 'Nagaur', label: 'Nagaur' },
      { value: 'Nathdwara', label: 'Nathdwara' },
      { value: 'Pali', label: 'Pali' },
      { value: 'Phalodi', label: 'Phalodi' },
      { value: 'Pushkar', label: 'Pushkar' },
      { value: 'Sawai Madhopur', label: 'Sawai Madhopur' },
      { value: 'Shahpura', label: 'Shahpura' },
      { value: 'Sikar', label: 'Sikar' },
      { value: 'Sirohi', label: 'Sirohi' },
      { value: 'Tonk', label: 'Tonk' },
      { value: 'Udaipur', label: 'Udaipur' },
    ],
    Sikkim: [
      { value: 'Gangtok', label: 'Gangtok' },
      { value: 'Gyalshing', label: 'Gyalshing' },
      { value: 'Lachung', label: 'Lachung' },
      { value: 'Mangan', label: 'Mangan' },
    ],
    'Tamil Nadu': [
      { value: 'Arcot', label: 'Arcot' },
      { value: 'Chengalpattu', label: 'Chengalpattu' },
      { value: 'Chennai', label: 'Chennai' },
      { value: 'Chidambaram', label: 'Chidambaram' },
      { value: 'Coimbatore', label: 'Coimbatore' },
      { value: 'Cuddalore', label: 'Cuddalore' },
      { value: 'Dharmapuri', label: 'Dharmapuri' },
      { value: 'Dindigul', label: 'Dindigul' },
      { value: 'Erode', label: 'Erode' },
      { value: 'Kanchipuram', label: 'Kanchipuram' },
      { value: 'Kanniyakumari', label: 'Kanniyakumari' },
      { value: 'Kodaikanal', label: 'Kodaikanal' },
      { value: 'Kumbakonam', label: 'Kumbakonam' },
      { value: 'Madurai', label: 'Madurai' },
      { value: 'Mamallapuram', label: 'Mamallapuram' },
      { value: 'Nagappattinam', label: 'Nagappattinam' },
      { value: 'Nagercoil', label: 'Nagercoil' },
      { value: 'Palayamkottai', label: 'Palayamkottai' },
      { value: 'Pudukkottai', label: 'Pudukkottai' },
      { value: 'Rajapalayam', label: 'Rajapalayam' },
      { value: 'Ramanathapuram', label: 'Ramanathapuram' },
      { value: 'Salem', label: 'Salem' },
      { value: 'Thanjavur', label: 'Thanjavur' },
      { value: 'Tiruchchirappalli', label: 'Tiruchchirappalli' },
      { value: 'Tirunelveli', label: 'Tirunelveli' },
      { value: 'Tiruppur', label: 'Tiruppur' },
      { value: 'Thoothukudi', label: 'Thoothukudi' },
      { value: 'Udhagamandalam', label: 'Udhagamandalam' },
      { value: 'Vellore', label: 'Vellore' },
    ],
    Telangana: [
      { value: 'Hyderabad', label: 'Hyderabad' },
      { value: 'Karimnagar', label: 'Karimnagar' },
      { value: 'Khammam', label: 'Khammam' },
      { value: 'Mahbubnagar', label: 'Mahbubnagar' },
      { value: 'Nizamabad', label: 'Nizamabad' },
      { value: 'Sangareddi', label: 'Sangareddi' },
      { value: 'Warangal', label: 'Warangal' },
    ],
    Tripura: [{ value: 'Agartala', label: 'Agartala' }],
    'Uttar Pradesh': [
      { value: 'Agra', label: 'Agra' },
      { value: 'Aligarh', label: 'Aligarh' },
      { value: 'Amroha', label: 'Amroha' },
      { value: 'Ayodhya', label: 'Ayodhya' },
      { value: 'Azamgarh', label: 'Azamgarh' },
      { value: 'Bahraich', label: 'Bahraich' },
      { value: 'Ballia', label: 'Ballia' },
      { value: 'Banda', label: 'Banda' },
      { value: 'Bara Banki', label: 'Bara Banki' },
      { value: 'Bareilly', label: 'Bareilly' },
      { value: 'Basti', label: 'Basti' },
      { value: 'Bijnor', label: 'Bijnor' },
      { value: 'Bithur', label: 'Bithur' },
      { value: 'Budaun', label: 'Budaun' },
      { value: 'Bulandshahr', label: 'Bulandshahr' },
      { value: 'Deoria', label: 'Deoria' },
      { value: 'Etah', label: 'Etah' },
      { value: 'Etawah', label: 'Etawah' },
      { value: 'Faizabad', label: 'Faizabad' },
      { value: 'Farrukhabad-cum-Fatehgarh', label: 'Farrukhabad-cum-Fatehgarh' },
      { value: 'Fatehpur', label: 'Fatehpur' },
      { value: 'Fatehpur Sikri', label: 'Fatehpur Sikri' },
      { value: 'Ghaziabad', label: 'Ghaziabad' },
      { value: 'Ghazipur', label: 'Ghazipur' },
      { value: 'Gonda', label: 'Gonda' },
      { value: 'Gorakhpur', label: 'Gorakhpur' },
      { value: 'Hamirpur', label: 'Hamirpur' },
      { value: 'Hardoi', label: 'Hardoi' },
      { value: 'Hathras', label: 'Hathras' },
      { value: 'Jalaun', label: 'Jalaun' },
      { value: 'Jaunpur', label: 'Jaunpur' },
      { value: 'Jhansi', label: 'Jhansi' },
      { value: 'Kannauj', label: 'Kannauj' },
      { value: 'Kanpur', label: 'Kanpur' },
      { value: 'Lakhimpur', label: 'Lakhimpur' },
      { value: 'Lalitpur', label: 'Lalitpur' },
      { value: 'Lucknow', label: 'Lucknow' },
      { value: 'Mainpuri', label: 'Mainpuri' },
      { value: 'Mathura', label: 'Mathura' },
      { value: 'Meerut', label: 'Meerut' },
      { value: 'Mirzapur-Vindhyachal', label: 'Mirzapur-Vindhyachal' },
      { value: 'Moradabad', label: 'Moradabad' },
      { value: 'Muzaffarnagar', label: 'Muzaffarnagar' },
      { value: 'Partapgarh', label: 'Partapgarh' },
      { value: 'Pilibhit', label: 'Pilibhit' },
      { value: 'Prayagraj', label: 'Prayagraj' },
      { value: 'Rae Bareli', label: 'Rae Bareli' },
      { value: 'Rampur', label: 'Rampur' },
      { value: 'Saharanpur', label: 'Saharanpur' },
      { value: 'Sambhal', label: 'Sambhal' },
      { value: 'Shahjahanpur', label: 'Shahjahanpur' },
      { value: 'Sitapur', label: 'Sitapur' },
      { value: 'Sultanpur', label: 'Sultanpur' },
      { value: 'Tehri', label: 'Tehri' },
      { value: 'Varanasi', label: 'Varanasi' },
    ],
    Uttarakhand: [
      { value: 'Almora', label: 'Almora' },
      { value: 'Dehra Dun', label: 'Dehra Dun' },
      { value: 'Haridwar', label: 'Haridwar' },
      { value: 'Mussoorie', label: 'Mussoorie' },
      { value: 'Nainital', label: 'Nainital' },
      { value: 'Pithoragarh', label: 'Pithoragarh' },
    ],
    'West Bengal': [
      { value: 'Alipore', label: 'Alipore' },
      { value: 'Alipur Duar', label: 'Alipur Duar' },
      { value: 'Asansol', label: 'Asansol' },
      { value: 'Baharampur', label: 'Baharampur' },
      { value: 'Bally', label: 'Bally' },
      { value: 'Balurghat', label: 'Balurghat' },
      { value: 'Bankura', label: 'Bankura' },
      { value: 'Baranagar', label: 'Baranagar' },
      { value: 'Barasat', label: 'Barasat' },
      { value: 'Barrackpore', label: 'Barrackpore' },
      { value: 'Basirhat', label: 'Basirhat' },
      { value: 'Bhatpara', label: 'Bhatpara' },
      { value: 'Bishnupur', label: 'Bishnupur' },
      { value: 'Budge Budge', label: 'Budge Budge' },
      { value: 'Burdwan', label: 'Burdwan' },
      { value: 'Chandernagore', label: 'Chandernagore' },
      { value: 'Darjeeling', label: 'Darjeeling' },
      { value: 'Diamond Harbour', label: 'Diamond Harbour' },
      { value: 'Dum Dum', label: 'Dum Dum' },
      { value: 'Durgapur', label: 'Durgapur' },
      { value: 'Halisahar', label: 'Halisahar' },
      { value: 'Haora', label: 'Haora' },
      { value: 'Hugli', label: 'Hugli' },
      { value: 'Ingraj Bazar', label: 'Ingraj Bazar' },
      { value: 'Jalpaiguri', label: 'Jalpaiguri' },
      { value: 'Kalimpong', label: 'Kalimpong' },
      { value: 'Kamarhati', label: 'Kamarhati' },
      { value: 'Kanchrapara', label: 'Kanchrapara' },
      { value: 'Kharagpur', label: 'Kharagpur' },
      { value: 'Cooch Behar', label: 'Cooch Behar' },
      { value: 'Kolkata', label: 'Kolkata' },
      { value: 'Krishnanagar', label: 'Krishnanagar' },
      { value: 'Malda', label: 'Malda' },
      { value: 'Midnapore', label: 'Midnapore' },
      { value: 'Murshidabad', label: 'Murshidabad' },
      { value: 'Nabadwip', label: 'Nabadwip' },
      { value: 'Palashi', label: 'Palashi' },
      { value: 'Panihati', label: 'Panihati' },
      { value: 'Purulia', label: 'Purulia' },
      { value: 'Raiganj', label: 'Raiganj' },
      { value: 'Santipur', label: 'Santipur' },
      { value: 'Shantiniketan', label: 'Shantiniketan' },
      { value: 'Shrirampur', label: 'Shrirampur' },
      { value: 'Siliguri', label: 'Siliguri' },
      { value: 'Siuri', label: 'Siuri' },
      { value: 'Tamluk', label: 'Tamluk' },
      { value: 'Titagarh', label: 'Titagarh' },
    ],
  };
  